config/routes.rb
Rails.application.routes.draw do
  get 'events/index'
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :pages, only: [:home] # Assuming you have a PagesController with a home action
  resources :events, only: [:new, :create, :index, :edit, :update, :destroy, :show]
    #publish method sends a POST request to the Eventbrite API endpoint to publish the event specified by its ID
    post 'events/:id/publish', to: 'events#publish', as: 'publish_event'




  resources :users, only: [:show, :edit, :update] do
    resource :profile, only: [:edit, :update] # Nested resource for user profiles
  end

  post 'oauth/', to:'oauths#receive'
  get  'oauth/', to:'oauths#show'

  get '/invite_page', to: 'pages#invite_page', as: :invite_page

  resources :guests, only: [:new, :create, :index, :edit, :update, :destroy]

  #post '/send_invitations', to: 'invitations#send_invitations', as: :send_invitations

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end




#<%= link_to 'Create New Event', new_event_path %>
#<%= link_to 'Publish Event', publish_event_path(@event.id), method: :post, data: { confirm: 'Are you sure you want to publish this event?' } %>


# Define custom routes for event categories
# get '/events/dashboard', to: 'events#dashboard', as: 'events_dashboard'
#get 'events/draft', to: 'events#draft', as: 'events_draft'
#get 'events/to_be_modified', to: 'events#to_be_modified', as: 'events_to_be_modified'
#get 'events/under_review', to: 'events#under_review', as: 'events_under_review'
#get 'events/published', to: 'events#published', as: 'events_published'
#get 'events/cancelled', to: 'events#cancelled', as: 'events_cancelled'
#get 'events/archived', to: 'events#archived', as: 'events_archived'

app/models/guest.rb
class Guest < ApplicationRecord
  belongs_to :user
  
  validates :first_name, :last_name, :email, presence: true
  validates :email, uniqueness: { scope: :user_id }
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  before_action :authenticate_user! # Assuming you want to authenticate users before managing guests
  before_action :set_guest, only: [:edit, :update, :destroy]

  def new
    @guest = Guest.new
  end

  def create
    @guest = Guest.new(guest_params)
    @guest.user = current_user
    if @guest.save
      # Handle successful creation
      redirect_to guests_path, notice: "Guest created successfully"
    else
      # Handle errors
      render :new
    end
  end

  def index
    @guests = Guest.all
  end

  def edit
    @guest = Guest.find(params[:id])

  end

  def update
    if @guest.update(guest_params)
      redirect_to guests_path, notice: "Guest updated successfully"
    else
      render :edit
    end
  end

  def destroy
    @guest.destroy
    redirect_to guests_path, notice: "Guest deleted successfully"
  end

  private

  def set_guest
    @guest = Guest.find(params[:id])
  end

  def guest_params
    params.require(:guest).permit(:first_name, :last_name, :email)
  end
end

app/views/guests/edit.html.erb
<div class="d-flex justify-content-center align-items-center vh-80 custom-editform  mt-5" style="color: white;">
  <div class="card-body d-flex flex-column newEventContainer  mt-3" style="color: #ffff; max-width: 500px;">
    <h5>Edit Guest Details</h5>
    <div class="guest-container mt-3">
      <%= simple_form_for @guest, url: guest_path(@guest), method: :patch, html: { class: 'container' } do |form| %>
        <div class="field mb-3" tabindex="1">
          <%= form.label :first_name do %>
            <i class="far fa-user"></i> <%= "First Name" %>
          <% end %>
          <%= form.text_field :first_name, class: "form-control", required: true %>
        </div>
        <div class="field mb-3" tabindex="2">
          <%= form.label :last_name do %>
            <i class="far fa-user"></i> <%= "Last Name" %>
          <% end %>
          <%= form.text_field :last_name, class: "form-control", required: true %>
        </div>
        <div class="field mb-3" tabindex="3">
          <%= form.label :email do %>
            <i class="far fa-envelope"></i> <%= "Email" %>
          <% end %>
          <%= form.email_field :email, class: "form-control", required: true %>
        </div>
        <%= form.submit "Update", class: "btn btn-dark mt-3" %>
      <% end %>
    </div>
  </div>
</div>

app/views/guests/index.html.erb
<div class="d-flex flex-column justify-content-center align-items-center" style="padding: 40px 95px;">
  <div class="sparkletitle w-100 text-center">
    <p>guest list</p>
  </div>
  <div class="card-body newEventContainer w-100 p-5"  style="color: #ffff;  max-width: 1050px;">
    <%= link_to new_guest_path, class: "plus-icon d-inline-flex align-items-center justify-content-center btn btn-flat btn-sm text-white", style: "position: absolute; top: 10px; right: 10px; width: 30px; height: 30px; border-radius: 50%;" do %>
      <i class="fa-solid fa-user-plus fa-lg" style="color: white;"></i>
    <% end %>
    <table class="table table-bordered text-center" style="border: none;">
      <thead class="border-0" >
        <tr style="border: 1px solid rgba(255, 255, 255, 0.28); ">
          <th scope="col" class="text-light" style="border: 1px solid rgba(255, 255, 255, 0.28); "><strong>First Name</strong></th>
          <th scope="col" class="text-light" style="border: 1px solid rgba(255, 255, 255, 0.28); "><strong>Last Name</strong></th>
          <th scope="col" class="text-light" style="border: 1px solid rgba(255, 255, 255, 0.28); "><strong>Email</strong></th>
          <th scope="col" class="text-light" style="border: 1px solid rgba(255, 255, 255, 0.28); "><strong>Action</strong></th>
        </tr>
      </thead>
      <tbody class="border-0" >
        <% @guests.each do |guest| %>
          <tr style="border: 1px solid rgba(255, 255, 255, 0.28);">
            <td class="text-light" style="border: 1px solid rgba(255, 255, 255, 0.28); "><%= guest.first_name %></td>
            <td class="text-light" style="border: 1px solid rgba(255, 255, 255, 0.28); "><%= guest.last_name %></td>
            <td class="text-light" style="border: 1px solid rgba(255, 255, 255, 0.28); "><%= guest.email %></td>
            <td class="text-light" style="border: 1px solid rgba(255, 255, 255, 0.28); ">

              <%= link_to edit_guest_path(guest), class: "edit-icon btn btn-flat btn-sm text-white" do %>
                <i class="fa-solid fa-pen-to-square"></i>
              <% end %>

              <%= link_to guest_path(guest), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete?"}, class: "delete-icon btn btn-flat btn-sm text-white" do %>
                <i class="fa-regular fa-trash-can"></i>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/guests/new.html.erb
<div class="d-flex justify-content-center align-items-center vh-80 custom-editform mt-5" style="color: white;">
  <div class="card-body d-flex flex-column newEventContainer" style="color: #ffff; max-width: 400px;">
    <h5>Add Guests</h5>
    <div class="guest-container mt-3">
      <%= form_with(model: @guest, url: guests_path, method: :post) do |form| %>
        <div class="field mb-3" tabindex="1">
          <%= form.label :first_name do %>
            <i class="far fa-user"></i> <%= "First Name" %>
          <% end %>
          <%= form.text_field :first_name, class: "form-control", required: true %>
        </div>
        <div class="field mb-3" tabindex="2">
          <%= form.label :last_name do %>
            <i class="far fa-user"></i> <%= "Last Name" %>
          <% end %>
          <%= form.text_field :last_name, class: "form-control", required: true %>
        </div>
        <div class="field mb-3" tabindex="3">
          <%= form.label :email do %>
            <i class="far fa-envelope"></i> <%= "Email" %>
          <% end %>
          <%= form.email_field :email, class: "form-control", required: true %>
        </div>

          <%= form.submit "Submit", class: "btn btn-dark mt-3" %>
      <% end %>
    </div>
  </div>

</div>