config/routes.rb
Rails.application.routes.draw do
  get 'events/index'
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :pages, only: [:home] # Assuming you have a PagesController with a home action
  resources :events, only: [:new, :create, :index, :edit, :update, :destroy, :show]
    #publish method sends a POST request to the Eventbrite API endpoint to publish the event specified by its ID
    post 'events/:id/publish', to: 'events#publish', as: 'publish_event'




  resources :users, only: [:show, :edit, :update] do
    resource :profile, only: [:edit, :update] # Nested resource for user profiles
  end

  post 'oauth/', to:'oauths#receive'
  get  'oauth/', to:'oauths#show'

  get '/invite_page', to: 'pages#invite_page', as: :invite_page

  resources :guests, only: [:new, :create, :index, :edit, :update, :destroy]

  #post '/send_invitations', to: 'invitations#send_invitations', as: :send_invitations

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end




#<%= link_to 'Create New Event', new_event_path %>
#<%= link_to 'Publish Event', publish_event_path(@event.id), method: :post, data: { confirm: 'Are you sure you want to publish this event?' } %>


# Define custom routes for event categories
# get '/events/dashboard', to: 'events#dashboard', as: 'events_dashboard'
#get 'events/draft', to: 'events#draft', as: 'events_draft'
#get 'events/to_be_modified', to: 'events#to_be_modified', as: 'events_to_be_modified'
#get 'events/under_review', to: 'events#under_review', as: 'events_under_review'
#get 'events/published', to: 'events#published', as: 'events_published'
#get 'events/cancelled', to: 'events#cancelled', as: 'events_cancelled'
#get 'events/archived', to: 'events#archived', as: 'events_archived'

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer footer-expand-sm footer-light footer-lewagon bg-transparent fluid text-center pt-5 pb-3 h-100 " >
   <div class="d-flex align-items-end justify-content-center mt-3 mb-3 " style="font-size: 11px; font-weight: lighter; letter-spacing: 1px;">
    <a href="#" style="color: white; "><i class="fab fa-twitter"></i></a>
    <a href="#" style="color: white; margin: 0% 2%; "><i class="fab fa-facebook"></i></a>
    <a href="#" style="color: white;"><i class="fab fa-instagram"></i></a>
  </div>
  <div class="text-light d-flex justify-content-center" style="font-size: 11px; font-weight: lighter; letter-spacing: 2px;">
    <p style="margin-right: 25px;">Copyright © 2024; All rights reserved.</p>
    <p class="">Crafted by the Le Wagon #1456 batchmates.</p>
  </div>
  <div class="d-flex align-items-end justify-content-evenly " style="font-size: 11px; font-weight: lighter; letter-spacing: 1px; padding: 0% 25%;">
    <a href="https://github.com/lae178456" target="_blank" class="text-light"><i class="fab fa-github"></i> Laetitia Steybe</a>
    <a href="https://github.com/ashakiran07" target="_blank" class="text-light"><i class="fab fa-github"></i> Asha Kiran Devkota</a>
    <a href="https://github.com/userJFD" target="_blank" class="text-light"><i class="fab fa-github"></i> Joel Fregno</a>
    <a href="https://github.com/louismn-dev" target="_blank" class="text-light"><i class="fab fa-github"></i> Louis Simon</a>
  </div>
</div>

app/views/shared/_modal_caraousel.html.erb
<div id="imageCarousel" class="carousel slide" data-bs-ride="carousel" style="max-width: 400px;">
        <div class="carousel-inner">
          <div class="carousel-item active">
            <%= image_tag("caraousel0.jpg",  class:"d-block w-100") %>
          </div>
          <div class="carousel-item">
            <%= image_tag("caraousel1.jpg",  class:"d-block w-100") %>
          </div>
          <div class="carousel-item">
            <%= image_tag("caraousel2.jpg",  class:"d-block w-100") %>
          </div>
          <div class="carousel-item">
            <%= image_tag("caraousel5.jpg",  class:"d-block w-100") %>
          </div>
          <div class="carousel-item">
            <%= image_tag("caraousel6.jpg",  class:"d-block w-100") %>
          </div>
          <div class="carousel-item">
            <%= image_tag("caraousel7.jpg",  class:"d-block w-100") %>
          </div>
      <!-- Add more carousel items with images -->
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#imageCarousel" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#imageCarousel" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>

app/views/shared/_modal_popup.html.erb
  <div class="modal fade" id="createEventModal" tabindex="-1" role="dialog" aria-labelledby="createEventModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-sm" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="createEventModalLabel">Create an Event</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <p>Do you have any upcoming events? Syncsparkle it and post in multiple platforms. Start here.</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-primary">Create</button>
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>

app/views/shared/_navbar.html.erb
<% if user_signed_in? %>
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon bg-transparent" >
<% else %>
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon bg-transparent" style="background: #101b38 !important;">
<% end %>
  <div class="container-fluid" style="padding: 0% 7%;">
    <%= link_to "/", class: "navbar-brand" do %>
      <%= image_tag "syncsparkle.png", class: "logo-img", alt: "Your Logo"%>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "HOME", root_path, class: "nav-link text-white" %>
          </li>
          <li class="nav-item">
            <%= link_to "NEW EVENT", new_event_path, class: "nav-link text-white" %>
          </li>
          <li class="nav-item">
            <%= link_to "DASHBOARD", events_path, class: "nav-link text-white" %>
          </li>
          <li class="nav-item">
            <%= link_to "ADD GUESTS", guests_path, class: "nav-link text-white" %>
          </li>
          <li class="nav-item">
            <%= link_to "LOGOUT", destroy_user_session_path, data: {turbo_method: :delete}, class: "nav-link text-white" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link text-white" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_newnavbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light shadow ">
  <div class="container-fluid">
    <%= link_to "", root_path, class: "navbar-brand" %>
  <a class="navbar-brand mx-auto" href="#">
      <%= image_tag "logo.png", class: "logo-img", alt: "Your Logo"%>
    </a>

    <div class="collapse navbar-collapse navitems" id="navbarSupportedContent">
      <div class="ms-auto flex">
        <% if user_signed_in? %>
        <%= link_to root_path do %>
          <small class="helptext", data-tooltip="Home">
          <%= image_tag "home2.png", alt: "Home", width: "32", height: "32"%>
          </small>
         <% end %>
         <%= link_to new_event_path do %>
        <small class="helptext", data-tooltip="Create Event">
          <%= image_tag "plus.png", alt: "New Event", width: "32", height: "32"%>
        </small>
         <% end %>
        <small class="helptext", data-tooltip="Sign Out">
          <%= link_to destroy_user_session_path, method: :delete do %>
          <%= image_tag "logout.png", alt: "Sign Out", width: "32", height: "32"%>
        </small>
          <% end %>
        <% else %>
        <%= link_to "log in", new_user_session_path, class: "btn outline-outline-secondary my-2 my-sm-0 ms-2 d-flex align-items-center justify-content-center", style: "color: #6c757d; border-color: #6c757d;"%>
        <%= link_to "sign up",  new_user_registration_path, class: "btn outline-outline-secondary my-2 my-sm-0 ms-2 d-flex align-items-center justify-content-center", style: "color: #6c757d; border-color: #6c757d;" %>
        <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/shared/_slider.html.erb
<!-- slider form old home page with reviews/commented out for later if abel to make it work with java scrip-->
<div id="container" data-controller="slider" class="reviewslider">
  <div id="slider-container" data-slider-target="slideElement">
    <span <%# onclick="slideRight()" %> class="btn" data-action="click->slider#right" id="left"></span>
    <div id="slider">
      <div class="slide">

      </div>
      <div class="slide">
        <div><p class="review">"Very easy to use, thanks to the tool the
        whole event organisation became very
        time efficient"</p></div>

        <div class="felx">
            <div class="avatar-container">
              <img src="avatar_image_url.jpg" alt="Avatar Image">
            </div>
          <div class="star-container">
            <span class="stars">
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            </span>
          </div>
        </div>
      </div>
      <div class="slide">
      <div><p class="review">"Very easy to use, thanks to the tool the
        whole event organisation became very
        time efficient"</p></div>
      </div>
      <div class="slide">
      <div><p class="review">"Very easy to use, thanks to the tool the
        whole event organisation became very
        time efficient"</p></div>
      </div>
      <div class="slide">
      <div><p class="review">"Very easy to use, thanks to the tool the
        whole event organisation became very
        time efficient"</p></div>
      </div>
      <div class="slide">
      <div><p class="review">"Very easy to use, thanks to the tool the
        whole event organisation became very
        time efficient"</p></div>
      </div>
      <div class="slide">
      <div><p class="review">"Very easy to use, thanks to the tool the
        whole event organisation became very
        time efficient"</p></div>
      </div>
      <div class="slide">
      <div><p class="review">"Very easy to use, thanks to the tool the
        whole event organisation became very
        time efficient"</p></div>
      </div>
      <div class="slide">
      <div><p class="review">"Very easy to use, thanks to the tool the
        whole event organisation became very
        time efficient"</p></div>
      </div>
      <span <%# onclick="slideLeft()" %> class="btn" data-action="click->slider#left" id="right"></span>
    </div>
  </div>
</div>
</div>