config/routes.rb
Rails.application.routes.draw do
  get 'events/index'
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :pages, only: [:home] # Assuming you have a PagesController with a home action
  resources :events, only: [:new, :create, :index, :edit, :update, :destroy, :show]
    #publish method sends a POST request to the Eventbrite API endpoint to publish the event specified by its ID
    post 'events/:id/publish', to: 'events#publish', as: 'publish_event'




  resources :users, only: [:show, :edit, :update] do
    resource :profile, only: [:edit, :update] # Nested resource for user profiles
  end

  post 'oauth/', to:'oauths#receive'
  get  'oauth/', to:'oauths#show'

  get '/invite_page', to: 'pages#invite_page', as: :invite_page

  resources :guests, only: [:new, :create, :index, :edit, :update, :destroy]

  #post '/send_invitations', to: 'invitations#send_invitations', as: :send_invitations

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end




#<%= link_to 'Create New Event', new_event_path %>
#<%= link_to 'Publish Event', publish_event_path(@event.id), method: :post, data: { confirm: 'Are you sure you want to publish this event?' } %>


# Define custom routes for event categories
# get '/events/dashboard', to: 'events#dashboard', as: 'events_dashboard'
#get 'events/draft', to: 'events#draft', as: 'events_draft'
#get 'events/to_be_modified', to: 'events#to_be_modified', as: 'events_to_be_modified'
#get 'events/under_review', to: 'events#under_review', as: 'events_under_review'
#get 'events/published', to: 'events#published', as: 'events_published'
#get 'events/cancelled', to: 'events#cancelled', as: 'events_cancelled'
#get 'events/archived', to: 'events#archived', as: 'events_archived'

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :eventlistings
  has_one_attached :photo

end

app/controllers/events_controller.rb
require 'httparty'

class EventsController < ApplicationController

  def new
    @event = Event.new
  end

  def index
    @events = current_user.events
    @past_events_count = Event.where('end_date < ?', Date.today).count
    if params[:query].present?
      @query = params[:query]
      @events = @events.where("title LIKE ?", "%#{params[:query]}%")
    end
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      redirect_to events_path, notice: 'Event was successfully updated.'
    else
      render :edit
    end
  end

  def show
    @event = Event.find(params[:id])

    api_key = ENV['API_KEY']

    redirect_url = "https://#{ENV['HOST']}/oauth/?event_id=#{@event.id}"
    # https://www.eventbrite.com/oauth/authorize?response_type=code&client_id=YOUR_API_KEY&redirect_uri=YOUR_REDIRECT_URI
    @eventbrite_oauth_link = "https://www.eventbrite.com/oauth/authorize?response_type=code&client_id=#{api_key}&redirect_uri=#{redirect_url}"
  end

  def edit
    @event = Event.find(params[:id])
  end

  def destroy
    @event = Event.find_by(id: params[:id])
    if @event
      @event.destroy
      redirect_to events_path, status: :see_other
    else
      flash[:error] = "Event not found"
      redirect_to events_path
    end
  end

  def create
  @event = Event.new(event_params)
  @event.user = current_user

  if @event.save
    create_event_listing
    redirect_to '/events', notice: 'Event was successfully created.'
  else
    render :new, status: :unprocessable_entity
  end
  end

  def events_views
    @total_views = Eventlistings.sum(:views)
  end

  private


  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:title, :description, :location, :start_date, :end_date, :online_event, :url, :categories, :user_id, :photo, :hashtags => [])
  end

  def create_event_listing
    @event.eventlistings.create(plattform_id: 1, views: rand(1..100))
  end

end


#def create
  #@event = Event.new(event_params)
  #@event.user = current_user
  #if @event.save
    #redirect_to '/events', notice: 'Event was successfully created.'
  #else
    #render :new, status: :unprocessable_entity
  #end
#end

app/views/events/_form.html.erb
<script src="https://cdn.jsdelivr.net/jquery.tagsinput/1.3.6/jquery.tagsinput.min.js"></script>

<%# <div class="row rounded homepagebackground" style="width: 90%; padding: 60px 0px; margin-right: auto; margin-left:auto; backdrop-filter: blur(13px); box-shadow: 22px 3px 36px -4px rgba(0,0,0,0.54);" >
  <div class="flat-form "> %>
<div data-controller="datepicker" class="d-flex justify-content-center align-items-center flex-column">
  <div class="card-body d-flex flex-column newEventContainer">
    <h3 style="text-transform: uppercase; letter-spacing: 4px; color: #ffff;">Create Event</h3>
    <div class="mt-4" style="color: #ffff">
      <%= simple_form_for(@event) do |e| %>
        <%= e.input :title %>
        <%= e.input :description %>
        <%= e.input :location %>
        <div class="d-flex flex-row">
          <div class="p-2 text-center">
            <%= e.input :start_date,
                as: :string,
                input_html: { data: { datepicker_target: "startDate" } },
                label_html: { style: 'text-align: center' }%>
          </div>
          <div class="p-2 text-center">
          <%= e.input :end_date,
              as: :string,
              input_html: { data: { datepicker_target: "endDate" } } %>
          </div>
          <div class="p-2 ml-auto">
          <%= e.input :online_event, as: :boolean, label: 'Online Event?' %>
          </div>
        </div>
        <%# <%= e.input :hashtags, as: :string, input_html: { id: 'tags-input' } %>
        <div class="d-flex flex-row">
          <div class="p-2">
            <%= e.input :categories, collection: ['Food', 'Sport', 'Concert', 'Business'], include_blank: 'Select Category' %>
          </div>
          <div class="p-2">
            <%= e.input :photo, as: :file %>
          </div>
        </div>
        <div class="d-flex justify-content-start form-actions createeventbtn btn-dark">
        <%= e.submit %>
        </div>
      <% end %>
    </div>
    </div>
  </div>
<%# </div> %>

<script>
  $(document).ready(function() {
    $('#tags-input').tagsInput({
      delimiter: [',', ' '],
      removeWithBackspace: true,
      onChange: function(input) {
        console.log('Tags input changed:', input.val());
        var tagsArray = input.val().split(/[,\s]+/);
        input.importTags(tagsArray.join(','));
}

    });
  });
</script>

app/views/events/edit.html.erb
<%= render "form", vinyl: @vinyl %>
 

app/views/events/index.html.erb
<%# the filter js function will use jQuery at the moment%>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="https://unpkg.com/isotope-layout@3/dist/isotope.pkgd.min.js"></script>

<div class="text-center h-100 d-flex justify-content-center align-items-center flex-column" >

      <div class="w-100" style="margin-bottom: 110px;">

        <div class="enventsintrocontainer ">
          <p>your dashboard contains <%= @events.count %> events</p>
          <div class="d-flex justify-content-center mt-3">
            <p class="enventssmtext" >Your are posting across 1 platform</p>
            <p class="enventssmtext" style="margin: 0px 35px 12px 35px; " id="total-views">Your total views are <span id="total-views-count"></p>
            <p class="enventssmtext">Currently, <%= pluralize(@past_events_count, 'event') %> have ended</p>
          </div>
        </div>

        <nav role="navigation" class="primary-navigation pt-1 pb-5">
          <ul>
            <li>
              <a href="#">Events &dtrif;</a>
              <ul class="dropdown">
                <li id="filter-all"><a href="#">All Events</a></li>
                <li id="filter-upcoming"><a href="#">Upcoming Events</a></li>
                <li id="filter-past"><a href="#">Past Events</a></li>
              </ul>
            </li>

            <li><a href="#">Categories &dtrif;</a>
              <ul class="dropdown filters category">
                <li class="active" data-filter="*"><a href="#!">All</a></li>
                <li data-filter=".Food"><a href="#!">Food</a></li>
                <li data-filter=".Sport"><a href="#!">Sport</a></li>
                <li data-filter=".Concert"><a href="#!">Concert</a></li>
                <li data-filter=".Business"><a href="#!">Business</a></li>
              </ul>
            </li>

            <li>
              <a href="#">Type &dtrif;</a>
              <ul class="dropdown filters online-offline">
                <li class="active" data-filter="*"><a href="#!">All</a></li>
                <li data-filter=".yes"><a href="#!">Online</a></li>
                <li data-filter=".no"><a href="#!">Offline</a></li>
              </ul>
            </li>
          </ul>
        </nav>

        <%#
        <button id="filter-all">Show All Events</button>
        <button id="filter-upcoming">Show Upcoming Events</button>
        <button id="filter-past">Show Past Events</button>

        <ul class="filters category" >
          <li class="active" data-filter="*"><a href="#!">All</a></li>
          <li data-filter=".Food"><a href="#!">Food</a></li>
          <li data-filter=".Sport"><a href="#!">Sport</a></li>
          <li data-filter=".Concert"><a href="#!">Concert</a></li>
          <li data-filter=".Business"><a href="#!">Business</a></li>
        </ul>

        <ul class="filters online-offline" >
          <li class="active" data-filter="*"><a href="#!">All</a></li>
          <li data-filter=".yes"><a href="#!">Online</a></li>
          <li data-filter=".no"><a href="#!">Offline</a></li>
        </ul>

        filter can be set by category%>

      </div>

      <div class="d-flex w-100 h-100 justify-content-evenly align-items-center flex-wrap" style="padding: 7% 0%;" >
        <% @events.each do |event| %>
            <%# # for each row 3 cards 1 per vinly %>
            <div class="mb-5 card-body-events justify-content-center flex-column h-100 item <%=event.categories%> <%= event.online_event ? 'yes' : 'no' %>" data-end-date="<%= event.end_date %>">
              <a href="<%= event_path(event) %>" class="card-link text-decoration-none">
                <div class="text-center">
                  <% if event.photo.attached? %>
                    <%= cl_image_tag event.photo.key, width: 400, height: 300, crop: :fill, class: "img-fluid card-img" %>
                  <% else %>
                    <%= image_tag("event_default.svg", class: "img-fluid eventimg") %>
                  <% end %>
                </div>
                <div class="details-container d-flex">
                  <div class="eventsinfo">
                    <h3> <%= event.title %></h3>
                    <div class="eventlocation d-flex flex-row justify-content-center">
                      <%= image_tag "location.png", alt: "location", width: "17", height: "15"%>
                      <h4 style="margin-left: 2%; "><%= event.location %></h4>
                    </div>
                    <% if event.hashtags? %>
                      <h4> <%= event.hashtags %></h4>
                    <% end %>
                    <h4> Posted on 1 platform</h4>
                     <% if event.eventlistings.present? %>
                       <% event.eventlistings.each do |eventlisting| %>
                       <h4 class="event-views" data-views="<%= event.eventlistings.sum(:views) %>"> Views: <%= event.eventlistings.sum(:views) %></h4>
                         <% end %>
                      <% else %>
                     <h4>0 views</h4>
                    <% end %>
                  </div>
                </div>
              </a>

          </div>
        <% end %>
      </div>

      <script>
        $(document).ready(function() {
          // Filter function
          $('.dropdown.filters li').on('click', function(e) {
            e.preventDefault();
            var filterValue = $(this).attr('data-filter');

            // Remove active class from all filters and add it to the clicked one
            $(this).siblings().removeClass('active');
            $(this).addClass('active');

            // Hide all cards and show only those matching the filter
            $('.card-body-events').hide().filter(filterValue).show();
          });

          // Initial filter setup
          $('#filter-all').click(); // Show all events initially
        });
      </script>

  <script>
$(document).ready(function() {
    // Initialize total views to 0
    var totalViews = 0;

    // Iterate over each event and sum up the views
    $('.card-body-events').each(function() {
        // Extract the views from the data attribute
        var views = parseInt($(this).find('.event-views').data('views')) || 0; // Parse integer, default to 0 if NaN
        totalViews += views;
    });

    // Display the total views in the element with id 'total-views-count'
    $('#total-views-count').text(totalViews);
  });
</script>

</div>

app/views/events/new.html.erb
<div>
<%= render "form", event: @event %>
</div>

app/views/events/show.html.erb
<div class="text-center h-100 d-flex justify-content-center align-items-center homepagebackgroundstatic" >

  <div class="w-100" style="margin-bottom: 110px;">
    <div class="d-flex flex-column align-items-center" >
      <div class="sparkletitle d-flex flex-wrap-reverse justify-content justify-content-around w-100" style="padding: 6% 1% 0% 1% !important;">
        <div style="width: 25%; margin: 0px; text-align: -webkit-right;">
          <%= link_to events_path, class: "btn-dark mt-1" do %>
            <i class="fa-solid fa-chevron-left" style="padding-right:10px;"></i> Back to Dashboard
          <% end %>
        </div>
        <p style="width: 50%; margin: 0px; ">event details</p>
        <div style="width: 25%; margin: 0px; "></div>
      </div>

          <div class="d-flex justify-content-center">
            <div class="">
              <div class="eventsdetail ml-2 d-flex flex-wrap justify-content-center" >
                <% if @event.photo.attached? %>
                  <%= cl_image_tag @event.photo.key, crop: :fill, class: "showimage h-100" %>
                <% else %>
                 <%= image_tag "event_default.svg", class: "showimage h-100" %>
                <% end %>
              <div class="m-5 detailevent" style="width: 50%;">
                <h3 style="font-weight: bold;"><%= @event.title %></h3>
                <p> Category: <%= @event.categories %></p>
                <p class="mb-1" >Event Location is <%= @event.location %></p>
                <% @event.eventlistings.each do |eventlisting| %>
                 <p> Views: <%= eventlisting.views %></p>
                <% end %>
                <p> <%= @event.description%>
                <p> <%= @event.start_date%></p>
                <% if @event.online_event? %>
                  <p>Online Event</p>
                <% else %>
                  <p>Onsite Event</p>
                <% end %>
                <% if @event.url? %>
                  <p><%= @event.url %></p>
                <% end %>
                <% if @event.hashtags? %>
                  <p><%= @event.hashtags %></p>
                <% end %>
                <div>
                  <small><%= link_to image_tag("rdpen.png", size: "40x40"), edit_event_path(@event), class: "float-right me-5" %></small>
                  <small><%= link_to image_tag("trash.png", size: "40x40"), event_path(@event), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete #{@event.title} on all platforms?"}, class: "float-right "%></small>
                </div>
              </div>
            </div>
          </div>

      </div>
    </div>

    <div class="d-flex flex-row align-items-center justify-content-center mt-5 mb-5">
      <%= link_to @eventbrite_oauth_link, class: "btn-dark m-3 eventbrite-icon" do %>
        Post to Eventbrite
      <% end %>

      <%= link_to invite_page_path(event_id: @event.id, event_title: @event.title, event_categories: @event.categories, event_location: @event.location, event_description: @event.description, event_start_date: @event.start_date, event_online: @event.online_event?, event_url: @event.url), class: "btn-dark m-3" do %>
         Invite Guests
      <% end %>
    </div>

  </div>
</div>

app/views/events/show.pdf.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Syncsparkle</title>
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type"/>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= wicked_pdf_stylesheet_link_tag "pdf" %>
  </head>
  <body>
    <div id="header">
      <!--= wicked_pdf_image_tag 'thumbnail.png', height: "30", width: "auto"-->
    </div>
    <%= yield %>
  </body>
</html>